[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools >= 40.8.0', 'wheel', 'numpy', 'matplotlib']

[tool.pytest.ini_options]
addopts = '-ra --tb=native --capture=sys -Wd'
python_files = 'test_*.py'
testpaths = 'test'
