name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
