name: codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate coverage report
        run: |
          pip install numpy matplotlib seaborn pytest pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
