name: release

on:
  release:
    types: [created]

jobs:
  pypi:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir build
          pip install -r requirements.txt
          python -m build .
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
