name: codecov
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pytest
        run: |
          pip install numpy matplotlib seaborn pytest pytest-cov
          pytest --cov=alpsplot
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
