name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Pytest
        run: pytest --cov=alpsplot --cov-report=xml
      - name: Upload Codecov
        uses: codecov/codecov-action@v2.1.0
